apiVersion: apps/v1
kind: Deployment
metadata:
  name: hw-hospital-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hw-hospital-api
  template:
    metadata:
      labels:
        app: hw-hospital-api
    spec:
      containers:
        - name: hw-hospital-api-container
          image: hr3000/hw_hospital_api:tagVersion
          ports:
            - containerPort: 3000
