apiVersion: apps/v1
kind: Deployment
metadata:
  name: hw-hospital-api-deployment
  namespace: default # Specify the namespace here
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hw-hospital-api
  template:
    metadata:
      labels:
        app: hw-hospital-api
    spec:
      containers:
        - name: hw-hospital-api-container
          image: public.ecr.aws/r7i3e5e9/hw-hospital-images:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: hw-service
  namespace: default # Specify the namespace here
spec:
  selector:
    app: hw-hospital-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer