version: '3.9'

services: 
  api: 
    build: .
    ports: 
      - 4000:3000
    environment:
      PORT: 3000
      MONGODBURI: mongodb+srv://hospitalcust01.tu8mog8.mongodb.net/
      DB_NAME: Hospital
      DB_USER: hr3000
      DB_PASSWORD: ia9vLUpL9TQPi1RC