###All Patients
GET http://localhost:3000/Patient

###create a patient list
POST http://localhost:3000/Patient
Content-Type:  application/json

{
    "Patient_id" : "100010",
    "Patient_name" : "Tim",
    "DOB": "20-may-1987",
    "Address1" : "Sports City",
    "City": "Dubai",
    "Country": "United Arab Emirates",
    "Nationality": "Indian",
    "Insurance": "Met life"
}


###Get a patient by ID
GET  http://localhost:3000/Patient/10000006


###Update patient by ID
PATCH  http://localhost:3000/Patient/65ca772ad0c04d391e4f1
Content-Type:  application/json

{
    "Patient_id" : 1000007
}

###Delete a patient by ID
DELETE http://localhost:3000/Patient/100006

### Exceptions
GET http://localhost:3000/yghgh

###test fetch
GET http://localhost:3000/test?name=Hari&dob=15-jan-87


###test fetch
POST http://localhost:3000/test
Content-Type: application/json

{
    "name": "Hari",
    "dob": "15-jan-87"
}