apiVersion: v1
kind: Service
metadata:
  name: hw-hospital-api-service
spec:
  selector:
    app: hw_hospital_api
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
