apiVersion: v1
kind: Service
metadata:
  name: agile_avengers-service
spec:
  selector:
    app: agile_avengers
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
